title: "Промокоды Нетпринт 2026"
description: "Актуальные промокоды Нетпринт — проверяются ежедневно. Скидка 30% на первый заказ."
url: "https://netprint-promo.github.io"
baseurl: "/netprint-promo"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

webmaster_verifications:
  yandex: "d4e8f6842363525a"
  google: "vNQ92qLg9UOFvDLhOBa-koWzRv7IZ_yeIwUTU3HSZjc"
